#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : dmenu
Version  : 4.8
Release  : 1
URL      : https://git.suckless.org/dmenu/snapshot/dmenu-4.8.tar.bz2
Source0  : https://git.suckless.org/dmenu/snapshot/dmenu-4.8.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : libXinerama-dev
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xft)

%description
dmenu - dynamic menu
====================
dmenu is an efficient dynamic menu for X.

%prep
%setup -q -n dmenu-4.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1525283729
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1525283729
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/usr/local/bin/dmenu
/usr/local/bin/dmenu_path
/usr/local/bin/dmenu_run
/usr/local/bin/stest
/usr/local/share/man/man1/dmenu.1
/usr/local/share/man/man1/stest.1
